export const COLUMN_DATA_REQUEST = 'COLUMN_DATA_DATA';
export const COLUMN_DATA_SUCCESS = 'COLUMN_DATA_SUCCESS';
export const COLUMN_DATA_ERROR = 'COLUMN_DATA_ERROR';

export const VARIANT_DATA_REQUEST = 'VARIANT_DATA_DATA';
export const VARIANT_DATA_SUCCESS = 'VARIANT_DATA_SUCCESS';
export const VARIANT_DATA_ERROR = 'VARIANT_DATA_ERROR';